global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      exported_namespace: 'docker-host-alpha'

scrape_configs:
  - job_name: clickhouse
    static_configs:
      - targets:
        - clickhouse:8123
    scrape_interval: 1m
    scrape_timeout: 30s
    metrics_path: "/metrics"
    basic_auth:
      username: 'metrics'
      password: 'GkcSxt5WD3a34j'