version: '2.1'

volumes:
    grafana_data: {}
    clickhouse_data: {}

services:

  grafana:
    image: grafana/grafana:9.3.1
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - "33000:3000"
    labels:
      org.label-schema.group: "monitoring"

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    volumes:
      - ./clickhouse/sql:/docker-entrypoint-initdb.d
      - ./clickhouse/config.d:/etc/clickhouse-server/config.d
      - ./clickhouse/users.d:/etc/clickhouse-server/users.d
      - ./clickhouse/format_schemas:/var/lib/clickhouse/format_schemas
    restart: unless-stopped
    expose:
      - 8123
    labels:
      org.label-schema.group: "monitoring"