version: '2.1'

volumes:
    prometheus_data: {}
    grafana_data: {}
    clickhouse_data: {}

services:

  prometheus:
    image: prom/prometheus:v2.40.5
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    expose:
      - 9090
    ports:
      - "39090:9090"
    labels:
      org.label-schema.group: "monitoring"

  grafana:
    image: grafana/grafana:9.3.1
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - "33000:3000"
    labels:
      org.label-schema.group: "monitoring"

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    volumes:
      - ./clickhouse/sql:/docker-entrypoint-initdb.d
      - ./clickhouse/config.d:/etc/clickhouse-server/config.d
      - ./clickhouse/users.d:/etc/clickhouse-server/users.d
    restart: unless-stopped
    expose:
      - 8123
    labels:
      org.label-schema.group: "monitoring"